### ISSUE TITLE
Build error: call to undeclared function?

### ISSUE THREAD

**Issue by keriszafir** [orangkucing/GenlockDongle#1]
I'm trying to compile the GenlockDongle, using Arduino IDE 2:1.0.5+dfsg2-4
Installed PinChangeInterrupt lib (v2.19 beta, v2.17 beta).

I can't build the project, the compiler throws "function not declared in this scope" errors for:
attachPinChangeInterrupt
digitalPinToInterrupt

Compiler output:

/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=8000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/PinChangeInt /tmp/build6444962272432391418.tmp/GenlockDongle.cpp -o /tmp/build6444962272432391418.tmp/GenlockDongle.cpp.o 
In file included from GenlockDongle.ino:49:0:
/usr/share/arduino/libraries/PinChangeInt/PinChangeInt.h:143:0: warning: "INLINE_PCINT" redefined [enabled by default]
   #define INLINE_PCINT inline
 ^
In file included from GenlockDongle.ino:49:0:
/usr/share/arduino/libraries/PinChangeInt/PinChangeInt.h:127:0: note: this is the location of the previous definition
 #define INLINE_PCINT
 ^
In file included from GenlockDongle.ino:49:0:
/usr/share/arduino/libraries/PinChangeInt/PinChangeInt.h: In member function ‘void PCintPort::PCint()’:
/usr/share/arduino/libraries/PinChangeInt/PinChangeInt.h:439:10: warning: variable ‘thisChangedPin’ set but not used [-Wunused-but-set-variable]
  uint8_t thisChangedPin; //MIKE
          ^
c_I2C.ino: In function ‘void __printBuf(byte*)’:
c_I2C.ino:32:16: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
c_I2C.ino: In function ‘void resetI2C()’:
c_I2C.ino:71:56: error: ‘attachPinChangeInterrupt’ was not declared in this scope
d_BacpacCommands.ino: In function ‘void checkCommands()’:
d_BacpacCommands.ino:281:25: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
e_Shutter.ino: In function ‘void setupShutter()’:
e_Shutter.ino:28:52: error: ‘digitalPinToInterrupt’ was not declared in this scope

**Comment by orangkucing** [comment]
please use arduino ide 1.5.7 or later

---=^..^= Hisashi Ito
⌘

**Comment by keriszafir** [comment]
Thanks;
I've tried to build it under 1.6.1 today (with PinChangeInterrupt 2.17beta or 2.19beta), still failed:

/home/elegant/arduino-1.6.1/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10601 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/elegant/arduino-1.6.1/hardware/arduino/avr/cores/arduino -I/home/elegant/arduino-1.6.1/hardware/arduino/avr/variants/standard -I/home/elegant/arduino-1.6.1/hardware/arduino/avr/libraries/Wire -I/home/elegant/arduino-1.6.1/libraries/PinChangeInt /tmp/build7119547337726275449.tmp/GenlockDongle.cpp -o /tmp/build7119547337726275449.tmp/GenlockDongle.cpp.o 
c_I2C.ino: In function 'void resetI2C()':
c_I2C.ino:71:56: error: 'attachPinChangeInterrupt' was not declared in this scope

**Comment by orangkucing** [comment]
Oops.

Your PinChangeInterrupt seems to be too old, too. Download the newest one.

2015-03-28 20:45 GMT+09:00 elegantandrogyne notifications@github.com:

**Comment by keriszafir** [comment]
Okay, tried the PinChangeInt from https://github.com/GreyGnome/PinChangeInt and it works.

Problem solved :)

Looks like the version at Google Code (where the Arduino's website points) is outdated. That's quite confusing, and worth mentioning in readme.
